pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir("${env.WORKSPACE}/frontend"){
                    sh "pwd"
                }

                echo 'Building'

                sh 'docker build -t ticket-frontend .'
            }
        }

        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/frontend"){
                    sh "pwd"
                }

                echo 'testing'

                sh 'npm test -- --watchAll=false'
            }
       
        }

        stage('Deploy') {
            steps {
                echo 'deploying'
            }
        }
    }
}