pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building'

                sh 'docker build -t ticket-frontend:0.1.0 ./frontend'
                sh 'docker tag foobarfarm/ticket-frontend:0.1.0 ./frontend'
            }
        }

        stage('Test') {
            steps {
                echo 'testing'
                sh 'npm install --prefix ./frontend --silent'
                sh 'npm test --prefix ./frontend -- --watchAll=false'
                sh 'rm -r ./frontend/node_modules'
            }
       
        }

        stage('Push Image to Docker Hub') {
            steps {
                echo 'Pushing image to DockerHub'

                withDockerRegistry([ credentialsId: "dockerhub-credentials", url: ""]) {
                    sh 'docker push foobarfarm/ticket-frontend:0.1.0'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}