pipeline {
    agent any

    stages {
        stage('Build and Test') {
            steps {
                echo 'Building'

                sh 'docker build -t foobarfarm/ticket-backend:0.1.5 ./backend' 

            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                echo 'Pushing image to DockerHub'

                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "dockerhub-credentials",
                usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                    sh 'docker login -u ${USERNAME} -p ${PASSWORD}'
                    sh 'docker push foobarfarm/ticket-backend:0.1.5'
                 }
            }
        }

        stage('Deploy') {
            steps {
                echo 'deploying'
            }
        }
    }
}