pipeline {
    agent any

    stages {
        stage('Build and Test') {
            steps {
                echo 'Building'

                sh 'docker build -t foobarfarm/ticket-backend:0.1.8 ./backend' 

            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                echo 'Pushing image to DockerHub'

                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "dockerhub-credentials",
                usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                    sh 'docker login -u ${USERNAME} -p ${PASSWORD}'
                    sh 'docker push foobarfarm/ticket-backend:0.1.8'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying K8s resources'

                // create Secret using values from Jenkins credentials
                // withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "database-credentials",
                // usernameVariable: 'DB_HOSTNAME', passwordVariable: 'DB_PASSWORD']]) {
                //     sh './kubernetes/scripts/exec-kubectl.sh ${DB_HOSTNAME} ${DB_PASSWORD} ./kubernetes/db-secret.yaml'
                // }

                // sh 'kubectl apply -f ./kubernetes/backend-pod.yaml'

                // sh 'kubectl apply -f ./kubernetes/backend-clusterip.yaml'
            }
        }
    }
}